package httpapi

import (
	"encoding/json"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestHTTPContract(t *testing.T) {
	h := New(slog.New(slog.NewJSONHandler(io.Discard, nil)))
	for _, tc := range []struct {
		method, path string
		status       int
	}{
		{"GET", "/healthz", 200}, {"GET", "/readyz", 200}, {"GET", "/v1", 200},
		{"POST", "/healthz", 405}, {"GET", "/missing", 404}, {"HEAD", "/healthz", 200},
	} {
		t.Run(tc.method+tc.path, func(t *testing.T) {
			r := httptest.NewRequest(tc.method, tc.path, nil)
			r.Header.Set("X-Request-ID", "untrusted")
			w := httptest.NewRecorder()
			h.ServeHTTP(w, r)
			if w.Code != tc.status || w.Header().Get("Content-Type") != "application/json" {
				t.Fatalf("unexpected response: %d %s", w.Code, w.Body.String())
			}
			id := w.Header().Get("X-Request-ID")
			if id == "" || id == "untrusted" {
				t.Fatal("request ID must be generated by server")
			}
			if tc.method == "HEAD" {
				if w.Body.Len() != 0 {
					t.Fatal("HEAD must have no body")
				}
				return
			}
			var payload map[string]json.RawMessage
			if err := json.Unmarshal(w.Body.Bytes(), &payload); err != nil {
				t.Fatal(err)
			}
			if tc.status >= 400 && len(payload["error"]) == 0 {
				t.Fatal("missing error envelope")
			}
			if tc.path == "/v1" && string(payload["capabilities"]) != "[]" {
				t.Fatal("must not advertise unimplemented generation")
			}
			if tc.status == 405 && w.Header().Get("Allow") != "GET, HEAD" {
				t.Fatal("missing Allow header")
			}
		})
	}
}

func TestLogsDoNotContainURLSecrets(t *testing.T) {
	var logs strings.Builder
	h := New(slog.New(slog.NewJSONHandler(&logs, nil)))
	h.ServeHTTP(httptest.NewRecorder(), httptest.NewRequest(http.MethodGet, "/secret-token?key=private-key", nil))
	if strings.Contains(logs.String(), "secret-token") || strings.Contains(logs.String(), "private-key") {
		t.Fatal("unknown URL or query leaked to logs")
	}
}
